"""
Pydantic schemas for meal plan-related API endpoints.

This module defines the request/response schemas for meal plan generation
and management, including meals, daily plans, and weekly meal plans.
"""

from typing import List, Optional, Dict
from pydantic import BaseModel, Field, ConfigDict


class MealItem(BaseModel):
    """
    Schema for a single meal item.

    This schema supports two modes:
    1. Overview mode (default): Basic meal information for browsing
    2. Detailed mode: Full recipe with ingredients, instructions, and nutrition
    """
    model_config = ConfigDict(exclude_none=True)

    # Required fields (always present)
    type: str = Field(..., description="Type of meal (breakfast, lunch, dinner, snack)")
    name: str = Field(..., description="Name of the meal")
    calories: int = Field(..., description="Estimated calories for this meal")
    description: str = Field(..., description="Description of the meal and its ingredients")

    # Optional detailed recipe fields (only when include_recipes=True)
    ingredients: Optional[List[str]] = Field(
        None,
        description="List of ingredients with quantities (e.g., '1 cup oats', '1/2 cup almond milk')"
    )
    servings: Optional[int] = Field(
        None,
        description="Number of servings this recipe yields"
    )
    prep_time_minutes: Optional[int] = Field(
        None,
        description="Preparation time in minutes"
    )
    cook_time_minutes: Optional[int] = Field(
        None,
        description="Cooking time in minutes"
    )
    instructions: Optional[List[str]] = Field(
        None,
        description="Step-by-step cooking instructions"
    )
    nutrition: Optional[Dict[str, str]] = Field(
        None,
        description="Detailed nutrition information (e.g., {'protein': '15g', 'carbs': '50g', 'fat': '10g', 'fiber': '8g'})"
    )


class DailyMealPlan(BaseModel):
    """Schema for a single day's meal plan."""
    day: str = Field(..., description="Day of the week or date")
    meals: List[MealItem] = Field(..., description="List of meals for this day")


class MealPlanResponse(BaseModel):
    """
    Schema for the complete meal plan response.

    This represents a weekly or multi-day meal plan with all meals organized by day,
    optionally including a summary of how the plan addresses user health goals.
    """
    plan: List[DailyMealPlan] = Field(..., description="List of daily meal plans")
    total_days: int = Field(..., description="Total number of days in the plan")
    average_calories_per_day: int = Field(..., description="Average daily calorie intake")
    health_goal_summary: Optional[str] = Field(
        None,
        description="Summary of how this meal plan addresses the user's health goals"
    )


class MealPlanRequest(BaseModel):
    """Schema for meal plan generation request."""
    num_days: int = Field(
        default=7,
        ge=1,
        le=14,
        description="Number of days for the meal plan (1-14)"
    )
    preferences: dict = Field(
        default_factory=dict,
        description="Optional preferences for meal generation"
    )


class LLMMealPlanResponse(BaseModel):
    """
    Schema for LLM-generated meal plan response.

    This simplified response schema is used for the LLM-based meal plan endpoint,
    providing the generated meal plan along with a health goal summary.
    """
    plan: List[DailyMealPlan] = Field(..., description="List of daily meal plans generated by LLM")
    health_goal_summary: Optional[str] = Field(
        None,
        description="Summary of how this meal plan addresses the user's health goals"
    )
